pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
use_ema: true
output_dir: "runs/logs/ppt_sd15"

train_data:
  resolution: 512
  transforms: ["center_crop", "random_flip"]
  datasets: [
    {
      name: "laion5b",
      prob: 0.4, # the probability of presence during training
      dataset_class: "LaionIterJsonDataset",
      anno_root: "laion5b:s3://llm-process/laion-5b/format/v020/laion2B-en/",
      aethetic_score_threshold: 5,
      bufsize: 100,
    },
    {
      name: "openimages",
      prob: 0.6, # the probability of presence during training
      dataset_class: "OpenImageBLIPaug_Dataset",
      anno_root: "openmmlab:s3://openmmlab/datasets/detection/OpenImages/OpenImages/train/",
      aethetic_score_threshold: 0.1,
      bufsize: None,

    }
  ]


learning_rate: 1e-5
train_batch_size: 16
dataloader_num_workers: 6
gradient_accumulation_steps: 8
gradient_checkpointing: true
checkpointing_steps: 2000
validation_steps: 1000
max_train_steps: 200000
max_grad_norm: 1
lr_scheduler constant_with_warmup: true
lr_warmup_steps: 2000

tracker_project_name: pptv1
report_to: tensorboard

resume_from_checkpoint: "latest"
