pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
output_dir: "runs"

train_data:
  resolution: 512
  datasets: [
    {
      name: "laion5b",
      # the probability of presence during training
      prob: 0.4,
      dataset_class: "LaionIterJsonDataset",
      # you may need to change the path to your own path
      client_prefix: "laion5b:",
      anno_root: "laion5b:s3://llm-process/laion-5b/format/v020/laion2B-en/",
      random_mask_root: "data/lama_mask/",
      aethetic_score_threshold: 5,
      bufsize: 100,
      resolution: 512,
    },
    {
      name: "openimages",
      prob: 0.6, # the probability of presence during training
      dataset_class: "OpenImageBLIPaug_Dataset",
      # you may need to change the path to your own path
      image_root: "openmmlab:s3://openmmlab/datasets/detection/OpenImages/OpenImages/train/",
      mask_root: "data/openimagev6/mask/",
      # prompt that describes segmented objects
      anno_root: "data/openimagev6/prompt",
      aethetic_score_threshold: 0.1,
      bufsize: null,
      resolution: 512,
    }
  ]


learning_rate: 1e-5
train_batch_size: 6
dataloader_num_workers: 32
gradient_accumulation_steps: 10
checkpointing_steps: 2000
validation_steps: 1000

tracker_project_name: ppt_brushnet
report_to: tensorboard

resume_from_checkpoint: "latest"
